# Análise de vendas de jogos


> **Briefing:**
>
> Você trabalha para a loja online Ice, que vende videogames no mundo todo. As avaliações de usuários e especialistas, gêneros, plataformas (por exemplo, Xbox ou PlayStation) e dados históricos sobre vendas de jogos estão disponíveis em fontes abertas.
> Você precisa identificar padrões que determinam se um jogo tem sucesso ou não. Isso vai permitir que você identifique possíveis sucessos e planeje campanhas publicitárias.
>
> Os dados disponibilizados remontam a 2016. Vamos imaginar que estamos em dezembro de 2016 e você está planejando uma campanha para 2017.
>
> O conjunto de dados contém uma coluna de "rating" (classificação) que armazena a classificação ESRB de cada jogo. O Entertainment Software Rating Board avalia o conteúdo de um jogo e atribui uma classificação etária, como Teen (Adolescente) ou Mature (Adulto).

**Descrição dos dados:**

-  Name (nome)
-  Platform (plataforma)
-  Year_of_Release (Ano de lançamento)
-  Genre (gênero)
-  NA_sales (vendas norte-americanas em milhões de USD)
-  EU_sales (vendas na Europa em milhões de USD)
-  JP_sales (vendas no Japão em milhões de USD)
-  Other_sales (vendas em outros países em milhões de USD)
-  Critic_Score (Pontuação crítica) (máximo de 100)
-  User_Score (Pontuação dos usuários) (máximo de 10)
-  Classificação (ESRB)

## Plano de trabalho

1. Pré-processamento
    - <input type="checkbox" checked> Renomear colunas    
    - <input type="checkbox" checked> Avaliar colunas com dados vazios
        - <input type="checkbox" checked> Preencher, remover ou manter colunas com dados vazios
    - <input type="checkbox" checked> Investigar duplicatas
        - <input type="checkbox" checked> Corrigir ou remover duplicatas
    - <input type="checkbox" checked> Corrigir tipos de dados
    - <input type="checkbox" checked> Enriquecimento dos dados
        - <input type="checkbox" checked> Criar coluna total de vendas, com a soma de todas as regiões
        - <input type="checkbox" checked> Converter as avaliações de críticos e usuários para a mesma escala, para poder compará-las
2. Análise exploratória 
    - <input type="checkbox" checked> Quantos jogos foram lançados por ano?
    - <input type="checkbox" checked> Analisar as vendas por plataforma:
        - <input type="checkbox" checked> Quais são as plataformas mais populares?
        - <input type="checkbox" checked> Quantos jogos foram lançados para cada uma por ano?
        - <input type="checkbox" checked> Por quanto tempo uma plataforma se mantém relevante?
    - <input type="checkbox" checked> Definir quais dados são mais relevantes para uma análise preditiva para 2017
    - <input type="checkbox" checked> Analisar quais são as plataformas com maior potencial de vendas
        - <input type="checkbox" checked> Comparar a distribuição da distribuição das vendas entre as plataformas
        - <input type="checkbox"> Como as avaliações afetam as vendas?
    - <input type="checkbox"> Como se distribuem os jogos por gênero?
        - <input type="checkbox"> Quais são os gêneros mais populares? E os menos?
        - <input type="checkbox"> O que podemos generalizar sobre os gêneros com vendas altas e baixas?
3. Categorização por região
    - <input type="checkbox"> Quais são as principais plataformas de cada região?
        - <input type="checkbox"> Quanto elas detem de mercado em cada região?
    - <input type="checkbox"> Quais são os gêneros mais populares em cada região?
    - <input type="checkbox"> Como a classificação ESRB afeta as vendas em cada região?
4. Testes de hipóteses
    - <input type="checkbox"> Testar hipótese: As classificações médias dos usuários das plataformas Xbox One e PC são as mesmas.
    - <input type="checkbox"> Testar hipótese: As classificações médias de usuários para os gêneros Action (ação) e Sports (esportes) são diferentes.
5. Conclusão

## Inicialização

In [236]:
# Importando bibiliotecas
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import plotly.express as px

In [210]:
# Importando o dataset
try:
    df = pd.read_csv('datasets/games.csv') # caminho local no windows
except FileNotFoundError:
    df = pd.read_csv('/datasets/games.csv') # caminho no ambiente da tripleten

In [211]:
# Visualizando os dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16713 non-null  object
 1   Platform         16715 non-null  object
 2   Year_of_Release  16446 non-null  float64
 3   Genre            16713 non-null  object
 4   NA_sales         16715 non-null  float64
 5   EU_sales         16715 non-null  float64
 6   JP_sales         16715 non-null  float64
 7   Other_sales      16715 non-null  float64
 8   Critic_Score     8137 non-null   float64
 9   User_Score       10014 non-null  object
 10  Rating           9949 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.4+ MB

In [212]:
# Visualizando as primeiras linhas do dataset
df.head()

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN

In [213]:
# Visualizando algumas amostras dos dados
df.sample(10, random_state=42)

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
3485,London 2012: The Official Video Game of the Ol...,X360,2012.0,Sports,0.07,0.44,0.00,0.07,NaN,NaN,NaN
5500,Etrian Odyssey,DS,2007.0,Role-Playing,0.19,0.02,0.09,0.02,75.0,8.5,T
16713,Spirits & Spells,GBA,2003.0,Platform,0.01,0.00,0.00,0.00,NaN,NaN,NaN
9489,RollerCoaster Tycoon,XB,2003.0,Strategy,0.10,0.03,0.00,0.00,62.0,8.3,E
12993,Rhapsody: A Musical Adventure,DS,2008.0,Role-Playing,0.05,0.00,0.00,0.00,67.0,6.8,E
12749,Men in Black The Series: Crashdown,PS,2001.0,Shooter,0.03,0.02,0.00,0.00,NaN,NaN,NaN
7270,Samurai Jack: The Amulet of Time,GBA,2003.0,Platform,0.16,0.06,0.00,0.00,63.0,tbd,T
2935,King Kong,2600,1981.0,Action,0.65,0.04,0.00,0.01,NaN,NaN,NaN
8739,Pressure Cooker,2600,1982.0,Action,0.14,0.01,0.00,0.00,NaN,NaN,NaN
2227,Cars,GC,2006.0,Racing,0.72,0.19,0.00,0.03,71.0,7,E

In [214]:
# Resumo estatístico das colunas numéricas
df.describe()

,Year_of_Release,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score
count,16446.000000,16715.000000,16715.000000,16715.000000,16715.000000,8137.000000
mean,2006.484616,0.263377,0.145060,0.077617,0.047342,68.967679
std,5.877050,0.813604,0.503339,0.308853,0.186731,13.938165
min,1980.000000,0.000000,0.000000,0.000000,0.000000,13.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,60.000000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,71.000000
75%,2010.000000,0.240000,0.110000,0.040000,0.030000,79.000000
max,2016.000000,41.360000,28.960000,10.220000,10.570000,98.000000

### Observações

**Formatação:**

- Renomear colunas para `snake_case` 

**Dados vazios:**

- Temos dados vazios em 6 colunas:
    - `Name`, `Year_of_Release`, `Genre` tem poucos valores vazios, avaliar possibilidade de remover as linhas
    - `Critics_Score`, `User_Score`, `Rating`: tem muitos valores, pode ser relevante pensar uma estratégia de preenchimento

**Tipos de dados:**

- Corrigir `Year_of_Release` de float para int, já que anos são inteiros
- `User_Score` precisa ser float, para realizarmos operações matemáticas, mas existem algumas linhas com a string 'tbd' que precisamos corrigir.

## Pré-processamento

In [215]:
# Renomeando colunas para snake_case
df.columns = df.columns.str.lower().str.replace(' ', '_')

# checando as colunas renomeadas
print(df.columns)
df.info()

Index(['name', 'platform', 'year_of_release', 'genre', 'na_sales', 'eu_sales',
       'jp_sales', 'other_sales', 'critic_score', 'user_score', 'rating'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16713 non-null  object
 1   platform         16715 non-null  object
 2   year_of_release  16446 non-null  float64
 3   genre            16713 non-null  object
 4   na_sales         16715 non-null  float64
 5   eu_sales         16715 non-null  float64
 6   jp_sales         16715 non-null  float64
 7   other_sales      16715 non-null  float64
 8   critic_score     8137 non-null   float64
 9   user_score       10014 non-null  object
 10  rating           9949 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.4+ MB

### Lidando com dados vazios

#### Colunas com poucas linhas vazias

In [216]:
# Checando vazios da coluna name
df[df['name'].isnull()]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
659,NaN,GEN,1993.0,NaN,1.78,0.53,0.00,0.08,NaN,NaN,NaN
14244,NaN,GEN,1993.0,NaN,0.00,0.00,0.03,0.00,NaN,NaN,NaN

In [217]:
# Checando vazios da coluna genre
df[df['genre'].isna()]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
659,NaN,GEN,1993.0,NaN,1.78,0.53,0.00,0.08,NaN,NaN,NaN
14244,NaN,GEN,1993.0,NaN,0.00,0.00,0.03,0.00,NaN,NaN,NaN

In [218]:
# Checando vazios da coluna year_of_release
df_year_null = df[df['year_of_release'].isna()]
print('Número de valores vazios na coluna year_of_release:', df['year_of_release'].isna().sum())
print(f'Porcentagem de jogos sem ano de lançamento: {(len(df_year_null) / len(df)) * 100:.2f}%')
print()
print(df_year_null['platform'].value_counts())

Número de valores vazios na coluna year_of_release: 269
Porcentagem de jogos sem ano de lançamento: 1.61%

platform
PS2     34
Wii     34
X360    30
DS      30
PS3     25
XB      21
2600    17
PC      17
PSP     16
GC      14
GBA     11
3DS      8
PS       7
N64      3
GB       1
PSV      1
Name: count, dtype: int64

In [219]:
df_year_null.head(10)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
183,Madden NFL 2004,PS2,NaN,Sports,4.26,0.26,0.01,0.71,94.0,8.5,E
377,FIFA Soccer 2004,PS2,NaN,Sports,0.59,2.36,0.04,0.51,84.0,6.4,E
456,LEGO Batman: The Videogame,Wii,NaN,Action,1.80,0.97,0.00,0.29,74.0,7.9,E10+
475,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,1.57,1.02,0.00,0.41,NaN,NaN,NaN
609,Space Invaders,2600,NaN,Shooter,2.36,0.14,0.00,0.03,NaN,NaN,NaN
627,Rock Band,X360,NaN,Misc,1.93,0.33,0.00,0.21,92.0,8.2,T
657,Frogger's Adventures: Temple of the Frog,GBA,NaN,Adventure,2.15,0.18,0.00,0.07,73.0,tbd,E
678,LEGO Indiana Jones: The Original Adventures,Wii,NaN,Action,1.51,0.61,0.00,0.21,78.0,6.6,E10+
719,Call of Duty 3,Wii,NaN,Shooter,1.17,0.84,0.00,0.23,69.0,6.7,T
805,Rock Band,Wii,NaN,Misc,1.33,0.56,0.00,0.20,80.0,6.3,T

In [220]:
# Removendo linhas valores vazios em year_of_release, name e genre
df = df.dropna(subset=['year_of_release', 'name', 'genre'])

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16444 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16444 non-null  object
 1   platform         16444 non-null  object
 2   year_of_release  16444 non-null  float64
 3   genre            16444 non-null  object
 4   na_sales         16444 non-null  float64
 5   eu_sales         16444 non-null  float64
 6   jp_sales         16444 non-null  float64
 7   other_sales      16444 non-null  float64
 8   critic_score     7983 non-null   float64
 9   user_score       9839 non-null   object
 10  rating           9768 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.5+ MB

##### Observações:
- As dados vazios de `name` e `genre` estão nas mesmas linhas, ambas foram removidas
- Decidi remover as linhas com dados vazio em `year_of_release` pois:
    - Apesar de alguns jogos terem vendas expressivas, o ano de lançamento é uma variável central para a análise temporal, preenche-lo pode tornar os resultados menos confiáveis
    - **1,61%** é um percentual aceitável dos dados para desconsiderar da análise.

#### Colunas com muitas linhas vazias

In [221]:
# Checando vazios da coluna critic_score
df_critic_null = df[df['critic_score'].isna()]
print('Número de valores vazios na coluna critic_score:', df['critic_score'].isna().sum())
print(f'Porcentagem de jogos sem critic_score: {(len(df_critic_null) / len(df)) * 100:.2f}%')

# Checando os valores únicos da coluna critic_score, incluindo os NaN
df['critic_score'].value_counts(dropna=False)

Número de valores vazios na coluna critic_score: 8461
Porcentagem de jogos sem critic_score: 51.45%

critic_score
NaN     8461
70.0     252
71.0     248
75.0     240
80.0     235
        ...
20.0       3
29.0       3
21.0       1
17.0       1
13.0       1
Name: count, Length: 82, dtype: int64

In [222]:
# Checando vazios da coluna user_score
df_user_null = df[df['user_score'].isna()]
print('Número de valores vazios na coluna user_score:', df['user_score'].isna().sum())
print(f'Porcentagem de jogos sem user_score: {(len(df_user_null) / len(df)) * 100:.2f}%')

# Checando os valores únicos da coluna user_score, incluindo os NaN
df['user_score'].value_counts(dropna=False)

Número de valores vazios na coluna user_score: 6605
Porcentagem de jogos sem user_score: 40.17%

user_score
NaN    6605
tbd    2376
7.8     322
8       285
8.2     276
       ...
1.9       2
9.6       2
0.9       2
0         1
9.7       1
Name: count, Length: 97, dtype: int64

In [223]:
# Checando vazios da coluna rating
df_rating_null = df[df['rating'].isna()]
print('Número de valores vazios na coluna rating:', df['rating'].isna().sum())
print(f'Porcentagem de jogos sem rating: {(len(df_rating_null) / len(df)) * 100:.2f}%')

# Checando os valores únicos da coluna rating, incluindo os NaN
df['rating'].value_counts(dropna=False)

Número de valores vazios na coluna rating: 6676
Porcentagem de jogos sem rating: 40.60%

rating
NaN     6676
E       3921
T       2905
M       1536
E10+    1393
EC         8
K-A        3
AO         1
RP         1
Name: count, dtype: int64

In [224]:
# Corrigindo os valores 'tbd' para NaN na coluna user_score
df['user_score'] = df['user_score'].replace('tbd', np.nan)

# Checando vazios da coluna user_score novamente após a correção
df_user_null = df[df['user_score'].isna()]
print('Número de valores vazios na coluna user_score:', df['user_score'].isna().sum())
print(f'Porcentagem de jogos sem user_score: {(len(df_user_null) / len(df)) * 100:.2f}%')

# Checando por virgulas nos scores e substituindo por pontos para garantir que sejam interpretados como números decimais
print('\nNúmero de valores com vírgula na coluna user_score: ', df['user_score'].str.contains(',', na=False).sum())

Número de valores vazios na coluna user_score: 8981
Porcentagem de jogos sem user_score: 54.62%

Número de valores com vírgula na coluna user_score:  0

In [225]:
# Substituindo NaN por 'N/A' na coluna rating
df['rating'] = df['rating'].fillna('N/A')

# Checando os valores únicos da coluna rating novamente, incluindo os NaN
print(df['rating'].value_counts(dropna=False))

rating
N/A     6676
E       3921
T       2905
M       1536
E10+    1393
EC         8
K-A        3
AO         1
RP         1
Name: count, dtype: int64

In [226]:
# Checando o dataframe após as limpezas
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16444 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16444 non-null  object
 1   platform         16444 non-null  object
 2   year_of_release  16444 non-null  float64
 3   genre            16444 non-null  object
 4   na_sales         16444 non-null  float64
 5   eu_sales         16444 non-null  float64
 6   jp_sales         16444 non-null  float64
 7   other_sales      16444 non-null  float64
 8   critic_score     7983 non-null   float64
 9   user_score       7463 non-null   object
 10  rating           16444 non-null  object
dtypes: float64(6), object(5)
memory usage: 1.5+ MB

#### Observações:
- Para coluna `rating` decidi preencher os valores vazios com N/A (Not Available) indicando que a classificação não está disponível. 
- Para `user_score` e `critic_score` a decisão foi de manter os valores vazios, pois:
    - Removê-los, significa perder um volume significativo dos dados (51%, apenas no caso de `critic_score`)
    - Substituir por 0 ou pela média/mediana introduziria um viés considerável nos dados e poderia distorcer análises
    - Mantê-los signfica que ao fazer análises de avaliação, trabalharemos com um subset menor dos dados, mas não compremetemos os resultados.
- Para `user_score`, ainda tinhamos uma quantidade considerável de linhas preenchidas com 'tbd' (To Be Defined), que decidi tratar como valores vazios. Substituindo-os para `NaN` para poder realizar a conversão para float.

### Checando duplicatas

In [227]:
# Checando por linhas duplicadas
print('Quantidade de linhas duplicadas:', df.duplicated().sum())

# Checando por linhas duplicadas considerando name, platform, year_of_release e genre
print('Quantidade de linhas duplicadas considerando name, platform, year_of_release e genre:', df.duplicated(subset=['name', 'platform', 'year_of_release', 'genre']).sum())

# Checando por duplicadas considerando apenas as colunas name, platform e year_of_release
print('Quantidade de linhas duplicadas considerando name, platform e year_of_release:', df.duplicated(subset=['name', 'platform', 'year_of_release']).sum())

# Checando por linhas duplicadas considerando name, platform, year_of_release e genre
print('Quantidade de linhas duplicadas considerando name, platform:', df.duplicated(subset=['name', 'platform']).sum())

Quantidade de linhas duplicadas: 0
Quantidade de linhas duplicadas considerando name, platform, year_of_release e genre: 1
Quantidade de linhas duplicadas considerando name, platform e year_of_release: 1
Quantidade de linhas duplicadas considerando name, platform: 3

In [228]:
# Imprimindo as linhas duplicadas considerando name e platform
duplicated_rows = df[df.duplicated(subset=['name', 'platform', 'year_of_release', 'genre'], keep=False)]
display(duplicated_rows)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
604,Madden NFL 13,PS3,2012.0,Sports,2.11,0.22,0.0,0.23,83.0,5.5,E
16230,Madden NFL 13,PS3,2012.0,Sports,0.00,0.01,0.0,0.00,83.0,5.5,E

In [229]:
# Removendo a linha duplicada
df = df.drop(index=16230)

# Checando o resultado
duplicated_rows = df[df.duplicated(subset=['name', 'platform', 'year_of_release', 'genre'], keep=False)]
display(duplicated_rows)

Empty DataFrame
Columns: [name, platform, year_of_release, genre, na_sales, eu_sales, jp_sales, other_sales, critic_score, user_score, rating]
Index: []

##### Observações:

- Encontrei uma instância de registro duplicado para o mesmo jogo, plataforma e ano de lançamento. 
- A coluna duplicada foi tratada como erro de registro, já que reproduzia o mesmos valores nos metadados e nas avaliações, além de 0 vendas em todas as regiões exceto em `eu_sales` com 0.01 (10 mil dólares), consideravelmente menor que o desvio padrão para `eu_sales` (~0.5), portanto estatisticamente pouco relevante.

### Corrigindo tipos de dados

In [230]:
# Convertendo year_of_release para inteiro
df['year_of_release'] = df['year_of_release'].astype(int)

# Convertendo user_score para float
df['user_score'] = pd.to_numeric(df['user_score'],errors='coerce')

# Checando se houve algum problema na conversão
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16443 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16443 non-null  object
 1   platform         16443 non-null  object
 2   year_of_release  16443 non-null  int64
 3   genre            16443 non-null  object
 4   na_sales         16443 non-null  float64
 5   eu_sales         16443 non-null  float64
 6   jp_sales         16443 non-null  float64
 7   other_sales      16443 non-null  float64
 8   critic_score     7982 non-null   float64
 9   user_score       7462 non-null   float64
 10  rating           16443 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 1.5+ MB

### Enriquecendo os dados

In [231]:
# Criando a coluna total_sales
df['total_sales'] = df['na_sales'] + df['eu_sales'] + df['jp_sales'] + df['other_sales']

# Checando o dataframe após a adição da coluna
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16443 entries, 0 to 16714
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16443 non-null  object
 1   platform         16443 non-null  object
 2   year_of_release  16443 non-null  int64
 3   genre            16443 non-null  object
 4   na_sales         16443 non-null  float64
 5   eu_sales         16443 non-null  float64
 6   jp_sales         16443 non-null  float64
 7   other_sales      16443 non-null  float64
 8   critic_score     7982 non-null   float64
 9   user_score       7462 non-null   float64
 10  rating           16443 non-null  object
 11  total_sales      16443 non-null  float64
dtypes: float64(7), int64(1), object(4)
memory usage: 1.6+ MB

In [232]:
# Exibindo uma amostra dos dados para verificar a nova coluna total_sales
df.sample(5, random_state=42)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,total_sales
4797,NCAA GameBreaker 2000,PS,1999,Sports,0.22,0.15,0.00,0.03,NaN,NaN,N/A,0.40
15039,Steel Battalion: Line of Contact,XB,2004,Simulation,0.02,0.01,0.00,0.00,70.0,8.0,T,0.03
9479,Shrek Super Party,XB,2002,Misc,0.10,0.03,0.00,0.00,33.0,8.0,E,0.13
8281,Hello Kitty: Happy Party Pals,GBA,2005,Misc,0.12,0.05,0.00,0.00,NaN,NaN,N/A,0.17
323,Call of Duty: Ghosts,PS4,2013,Shooter,1.78,1.43,0.05,0.57,78.0,3.7,M,3.83

In [233]:
# Multiplicando a coluna user_score por 10 para que fique na mesma escala do critic_score
df['user_score'] = df['user_score'] * 10

# Exibindo uma amostra dos dados para verificar a nova escala da coluna user_score
df.sample(5, random_state=42)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,total_sales
4797,NCAA GameBreaker 2000,PS,1999,Sports,0.22,0.15,0.00,0.03,NaN,NaN,N/A,0.40
15039,Steel Battalion: Line of Contact,XB,2004,Simulation,0.02,0.01,0.00,0.00,70.0,80.0,T,0.03
9479,Shrek Super Party,XB,2002,Misc,0.10,0.03,0.00,0.00,33.0,80.0,E,0.13
8281,Hello Kitty: Happy Party Pals,GBA,2005,Misc,0.12,0.05,0.00,0.00,NaN,NaN,N/A,0.17
323,Call of Duty: Ghosts,PS4,2013,Shooter,1.78,1.43,0.05,0.57,78.0,37.0,M,3.83

##### Observações:

- Foi criada uma coluna `total_sales` para poder fazer analises do total de vendas, independente da região.
- Multiplique a coluna `user_score` por 10, para que fique na mesma escala de `critic_score`, facilitando a comparação entre as duas em visualizações e eventuais operações artiméticas.

## Análise exploratória

### Análise por ano

In [248]:
# Agrupando jogos por ano de lançamento
df_grouped_year = df.groupby('year_of_release').agg({
    'name': 'count',
    'total_sales': 'sum',
    'critic_score': 'mean',
    'user_score': 'mean',
    'platform': 'nunique'
}).reset_index()

df_grouped_year.rename(columns={'name': 'game_count', 'platform': 'platform_count'}, inplace=True)

df_grouped_year.sample(10, random_state=42)

,year_of_release,game_count,total_sales,critic_score,user_score,platform_count
17,1997,289,201.07,85.294118,84.722222,6
13,1993,60,45.99,NaN,NaN,5
4,1984,14,50.35,NaN,NaN,2
29,2009,1426,658.82,67.554531,69.907166,7
35,2015,606,267.98,72.871111,66.659933,10
25,2005,939,457.82,68.819847,75.096055,8
6,1986,21,37.08,NaN,NaN,2
26,2006,1006,517.71,67.338710,72.472826,10
24,2004,762,418.68,69.393939,77.505112,7
16,1996,263,199.15,89.875000,84.000000,8

In [249]:
# Criando um gráfico de com o total de jogos lançados por ano e a evolução das vendas totais ao longo dos anos
fig = px.bar(df_grouped_year, x='year_of_release', y='game_count', title='Número de Jogos Lançados por Ano')
fig.add_scatter(x=df_grouped_year['year_of_release'], y=df_grouped_year['total_sales'], mode='lines+markers', name='Vendas Totais')
fig.update_layout(xaxis_title='Ano de Lançamento', yaxis_title='Número de Jogos / Vendas Totais (em milhões USD)')
fig.show()

##### Observações:

- Os dados mais relantes para nosso objetivo, **planejar uma campanha para 2017** estão na fatia dos anos 2010, pois representam o período mais recente do mercado.
- Existe um boom de lançamentos em torno de 2008 (entre 2005 e 2011).
- Podemos desconsiderar os dados dos anos 80 e primeira metade dos anos 90, por terem um baixo volume e serem temporalmente bastante distantes do nosso objetivo. 
- A redução após 2012 não necessariamente representa uma retração da indústria de jogos, mas pode refletir limitações do dataset, mudanças no modelo de distribuição digital, transição de gerações de consoles e a consolidação de jogos como serviço, reduzindo a frequência de novos lançamentos físicos. *Vamos continuar a investigação, analisando as plataformas representadas nos dados*

### Análise das plataformas

In [265]:
# Identificando as plataformas presentes no dataset
print('Plataformas distintas no dataset:', df['platform'].unique())
print('Número de plataformas distintas:', df['platform'].nunique())

Plataformas distintas no dataset: ['Wii' 'NES' 'GB' 'DS' 'X360' 'PS3' 'PS2' 'SNES' 'GBA' 'PS4' '3DS' 'N64'
 'PS' 'XB' 'PC' '2600' 'PSP' 'XOne' 'WiiU' 'GC' 'GEN' 'DC' 'PSV' 'SAT'
 'SCD' 'WS' 'NG' 'TG16' '3DO' 'GG' 'PCFX']
Número de plataformas distintas: 31

In [301]:
# Agregando dados por plataforma
df_grouped_platform = df.groupby('platform').agg({
    'name': 'count',
    'total_sales': 'sum',
    'year_of_release': 'nunique'
}).sort_values(by='total_sales', ascending=False).reset_index()

df_grouped_platform.rename(columns={'name': 'game_count', 'year_of_release': 'year_count'}, inplace=True)

display(df_grouped_platform.head(20))

top_10_platforms = df_grouped_platform['platform'].head(10).tolist()

print('Top 10 plataformas mais populares por total em vendas:', top_10_platforms)

   platform  game_count  total_sales  year_count
0       PS2        2127      1233.56          12
1      X360        1232       961.24          12
2       PS3        1305       931.33          11
3       Wii        1286       891.18          11
4        DS        2121       802.78          11
5        PS        1190       727.58          10
6       PS4         392       314.14           4
7       GBA         811       312.88           8
8       PSP        1193       289.53          12
9       3DS         512       257.81           6
10       PC         957       255.76          26
11       GB          97       254.43          13
12       XB         803       251.57           9
13      NES          98       251.05          12
14      N64         316       218.01           7
15     SNES         239       200.04          10
16       GC         542       196.73           7
17     XOne         247       159.32           4
18     2600         116        86.48          10
19     WiiU         147        82.19           5

Top 10 plataformas mais populares por total em vendas: ['PS2', 'X360', 'PS3', 'Wii', 'DS', 'PS', 'PS4', 'GBA', 'PSP', '3DS']

In [264]:
# Criando um gráfico para visualizar a evolução das vendas totais por plataforma, usando plotly express
fig = px.bar(df_grouped_platform.sort_values('total_sales'), x='total_sales', y='platform', title='Vendas Totais por Plataforma')
fig.update_layout(yaxis_title='Plataforma', xaxis_title='Vendas Totais (em milhões USD)')
fig.show()

In [288]:
# Agrupando por ano e plataforma para analisar a evolução das vendas por plataforma ao longo dos anos
df_grouped_year_platform = df.groupby(['year_of_release', 'platform']).agg({
    'name': 'count',
    'total_sales': 'sum',
    'critic_score': 'mean',
    'user_score': 'mean'
}).reset_index()

# Renomeando colunas
df_grouped_year_platform.rename(columns={'name': 'game_count'}, inplace=True)

In [296]:
# Criando um heatmap para analisar a evolução das vendas por plataforma ao longo dos anos
fig = px.density_heatmap(df_grouped_year_platform, x='year_of_release', y='platform', z='total_sales', title='Evolução das Vendas por Plataforma ao Longo dos Anos', color_continuous_scale='Reds', width=1200, height=800)
fig.update_layout(xaxis_title='Ano de Lançamento', yaxis_title='Plataforma', coloraxis_colorbar_title='Vendas Totais (em milhões USD)')
fig.show()

In [297]:
# Criando um heatmap para analisar a evolução dos lançamentos de jogos por plataforma ao longo dos anos
fig = px.density_heatmap(df_grouped_year_platform, x='year_of_release', y='platform', z='game_count', title='Lançamentos por Plataforma ao Longo dos Anos', color_continuous_scale='Reds', width=1200, height=800)
fig.update_layout(xaxis_title='Ano de Lançamento', yaxis_title='Plataforma', coloraxis_colorbar_title='Número de Jogos')
fig.show()

### Observações:

- O ciclo de vida de uma plataforma parece durar em **torno de 10 anos**, como pode ser observados nos mapas de calor de vendas e lançamentos de jogos:
    - Plataformas muito populares como o PlayStation (PS), PlayStation2 (PS2) e o Nintendo DS (DS) já não registram vendas a partir de 2015.
    - O período de entre 2010 a 2014 marca a transição para uma nova geração de consoles: XboxOne, PS4, WiiU, 3DS. Observável pelas células do topo direito do heatmap se tornando mais escuras em volume de vendas e/ou lançamentos, enquanto a geração anterior entra em declínio.  
- *Alguns fatores podem ajudar a explicar a queda após 2012:*
    - O dataset parece estar mais enviesado a lançamentos de consoles, tendo menos representação para PC e não registrando jogos para dispositivos mobile (Android e iOS). Após 2012, a Steam (plataforma de venda de jogos para PC da Valve) se estabelece a ganha popularidade. 
    - Outro dado relevate, é que nas gerações mais recentes, a indústria de jogos vem investindo mais ciclos de desenvolvimento mais longos, micro-transações, com pacotes de expansão e DLCs e distribuição digital, ao invés de mídia física. Todos esses fatores parecem estar ausentes do dataset, o que pode explicar a queda de lançamentos e registros de vendas. Algumas dessas tendências, podem ser observadas [relatório da ESA](https://www.theesa.com/u-s-consumer-video-game-spending-totaled-57-2-billion-in-2023).
- **Decisões para aprofundar a análise:**
    - Incluir nas análises de avaliações, classificação e genêros: 
        - As 10 plataformas mais populares em vendas: 'PS2', 'X360', 'PS3', 'Wii', 'DS', 'PS', 'PS4', 'GBA', 'PSP', '3DS'
        - Mais as plataformas novas e com lançamentos recentes (incluindo PC), que não estão nessa lista: 'PC', 'XOne', 'WiiU', 'PSV' 
        - Com  base nessas plataformas, o período analisado será de **1995 até 2016**. Com análises mais direcionadas conduzidas em cima da transição de plataformas observando o período de **2005 a 2016**.

### Filtrando os dados mais relevantes

In [337]:
## Criando uma lista com as plataformas selecionadas:

# Criando uma lista com os critérios de seleção: plataformas com jogos com vendas totais maiores que 0 e lançados a partir de 2012
current_platforms = df[(df['total_sales'] > 0) & (df['year_of_release'] >= 2010)]['platform'].unique().tolist()

print('Plataformas com jogos lançados a partir de 2010 e vendas registradas:', current_platforms)

# Incluindo as top10 plataformas mais populares por total em vendas na lista de plataformas selecionadas
selected_platforms = current_platforms.copy()
for platform in top_10_platforms:
    if platform not in current_platforms:
        selected_platforms.append(platform)

print('Plataformas selecionadas para análise:', selected_platforms)

Plataformas com jogos lançados a partir de 2010 e vendas registradas: ['X360', 'PS3', 'DS', 'PS4', '3DS', 'Wii', 'XOne', 'WiiU', 'PC', 'PSP', 'PSV', 'PS2']
Plataformas selecionadas para análise: ['X360', 'PS3', 'DS', 'PS4', '3DS', 'Wii', 'XOne', 'WiiU', 'PC', 'PSP', 'PSV', 'PS2', 'PS', 'GBA']

In [ ]:
## Criando um segundo dataframe apenas com as plataformas com jogos com vendas registradas e lançados a partir de 2010
# Esse dataframe será usado para análises de padrões e tendências mais recentes no mercado
df_recent = df[
    (df['year_of_release'] >= 2010) &
    (df['platform'].isin(current_platforms)) &
    (df['total_sales'] > 0) 
].reset_index()

df_recent.info()
df_recent.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5231 entries, 0 to 5230
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            5231 non-null   int64
 1   name             5231 non-null   object
 2   platform         5231 non-null   object
 3   year_of_release  5231 non-null   int64
 4   genre            5231 non-null   object
 5   na_sales         5231 non-null   float64
 6   eu_sales         5231 non-null   float64
 7   jp_sales         5231 non-null   float64
 8   other_sales      5231 non-null   float64
 9   critic_score     2310 non-null   float64
 10  user_score       2489 non-null   float64
 11  rating           5231 non-null   object
 12  total_sales      5231 non-null   float64
dtypes: float64(7), int64(2), object(4)
memory usage: 531.4+ KB

,index,year_of_release,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,total_sales
count,5231.000000,5231.000000,5231.000000,5231.000000,5231.000000,5231.000000,2310.000000,2489.000000,5231.000000
mean,9013.319824,2012.376410,0.215655,0.160491,0.058180,0.050885,70.445887,66.785858,0.485211
std,4949.008063,2.032708,0.615532,0.466042,0.228066,0.151163,13.564257,15.219520,1.240858
min,14.000000,2010.000000,0.000000,0.000000,0.000000,0.000000,13.000000,2.000000,0.010000
25%,4767.000000,2011.000000,0.000000,0.000000,0.000000,0.000000,62.000000,59.000000,0.040000
50%,9385.000000,2012.000000,0.050000,0.020000,0.000000,0.010000,73.000000,70.000000,0.130000
75%,13472.000000,2014.000000,0.180000,0.130000,0.040000,0.040000,80.000000,78.000000,0.400000
max,16714.000000,2016.000000,15.000000,9.090000,5.650000,3.960000,97.000000,93.000000,21.820000

In [ ]:
## Criando um dataframe filtrado com as decisões da última etapa, ou seja, jogos lançados a partir de 1995, com vendas registradas e pertencentes às plataformas selecionadas

# Esse data frame será usado para análises de padrões em generos e scores e sua correlação com vendas ao longos dos anos. 
# Ele é mais abrangente do que o df_recent, pois inclui jogos lançados a partir de 1995, permitindo uma análise histórica mais completa

df_full = df[
    (df['year_of_release'] >= 1995) &
    (df['platform'].isin(selected_platforms)) &
    (df['total_sales'] > 0) 
].reset_index()

df_full.info()
df_full.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13916 entries, 0 to 13915
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            13916 non-null  int64
 1   name             13916 non-null  object
 2   platform         13916 non-null  object
 3   year_of_release  13916 non-null  int64
 4   genre            13916 non-null  object
 5   na_sales         13916 non-null  float64
 6   eu_sales         13916 non-null  float64
 7   jp_sales         13916 non-null  float64
 8   other_sales      13916 non-null  float64
 9   critic_score     6821 non-null   float64
 10  user_score       6516 non-null   float64
 11  rating           13916 non-null  object
 12  total_sales      13916 non-null  float64
dtypes: float64(7), int64(2), object(4)
memory usage: 1.4+ MB

,index,year_of_release,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,total_sales
count,13916.000000,13916.000000,13916.000000,13916.000000,13916.000000,13916.000000,6821.000000,6516.000000,13916.000000
mean,8488.211555,2007.815895,0.249491,0.154516,0.063525,0.053529,68.820554,70.627379,0.521061
std,4872.916146,4.750614,0.731331,0.530882,0.263946,0.202260,13.944340,14.973660,1.506706
min,0.000000,1995.000000,0.000000,0.000000,0.000000,0.000000,13.000000,0.000000,0.010000
25%,4238.750000,2005.000000,0.000000,0.000000,0.000000,0.000000,60.000000,63.000000,0.060000
50%,8524.500000,2008.000000,0.070000,0.020000,0.000000,0.010000,71.000000,74.000000,0.160000
75%,12771.250000,2011.000000,0.230000,0.120000,0.030000,0.040000,79.000000,81.000000,0.460000
max,16714.000000,2016.000000,41.360000,28.960000,6.500000,10.570000,98.000000,97.000000,82.540000

### Definindo as plataformas com potencial de lucro

In [363]:
# Agregando por plataforma e ano de lançamento para analisar a evolução das vendas por plataforma ao longo dos anos
df_recent_by_platform = df_recent.groupby(['year_of_release', 'platform']).agg({
    'name': 'count',
    'total_sales': 'sum',
    'critic_score': 'mean',
    'user_score': 'mean'
}).reset_index()

df_recent_by_platform.rename(columns={'name': 'game_count', 'critic_score': 'mean_critic_score', 'user_score': 'mean_user_score'}, inplace=True)
df_recent_by_platform.head(10)

,year_of_release,platform,game_count,total_sales,mean_critic_score,mean_user_score
0,2010,DS,323,85.02,67.732143,72.628571
1,2010,PC,90,24.28,73.016393,68.223881
2,2010,PS3,181,142.17,67.507937,67.229508
3,2010,PSP,188,35.04,68.697674,72.386364
4,2010,Wii,253,127.95,65.194805,71.241935
5,2010,X360,182,170.03,65.713235,66.893130
6,2011,3DS,116,63.20,62.693548,64.894737
7,2011,DS,153,26.18,64.684211,69.800000
8,2011,PC,139,35.03,72.703297,64.990099
9,2011,PS3,215,156.78,70.407407,67.805970

In [341]:
# Criando um boxplot para analisar a distribuição das vendas por plataforma ao longo dos anos
fig = px.box(
    df_recent,
    x='platform',
    y='total_sales',
    points='outliers',
    hover_name='name',
    title='Distribuição das Vendas por Plataforma (Jogos Lançados a partir de 2010)',
    width=1400,
    height=800,
)
fig.update_traces(marker=dict(size=6), hovertemplate='<b>%{hovertext}</b><br>Plataforma: %{x}<br>Vendas: %{y:.2f}M')
fig.update_layout(xaxis_title='Plataforma', yaxis_title='Vendas Totais (em milhões USD)')
fig.show()

Parece que o mercado de jogos é largamente influenciado por grandes títulos. Para uma visualização geral por plataforma, vamos olhar para o total de vendas agrupado por ano de lançamento dos jogos.

In [342]:
# Plotando novamente com os dados agrupados por ano, para suavizar os outliters
fig = px.box(
    df_recent_by_platform,
    x='platform',
    y='total_sales',
    points='outliers',
    title='Distribuição das Vendas por Plataforma (Dados Agrupados por Ano)',
    width=1400,
    height=800,
)
fig.update_layout(xaxis_title='Plataforma', yaxis_title='Vendas Totais (em milhões USD)')
fig.show()

In [383]:
# Criando um gráfico de linha para visualizar a evolução das vendas totais ao longo dos anos
# Filtrando para os dados até 2015, já que 2016 pode ter dados incompletos e afetar a análise de tendências
fig = px.line(df_recent_by_platform[df_recent_by_platform['year_of_release'] <= 2015], x='year_of_release', y='total_sales', color='platform', title='Evolução das Vendas Totais por Plataforma (Jogos Lançados a partir de 2010)', width=1400, height=800)
fig.update_layout(xaxis_title='Ano de Lançamento', yaxis_title='Vendas Totais (em milhões USD)')
fig.show()

In [386]:
# Criando um gráfico de barra para visualizar a evolução das vendas totais ao longo dos anos
fig = px.bar(df_recent_by_platform, 
             x='year_of_release', 
             y='total_sales', 
             color='platform', 
             title='Evolução das Vendas Totais por Plataforma (Jogos Lançados a partir de 2010)', 
             width=1400, 
             height=800,
             barmode='stack')
fig.update_layout(xaxis_title='Ano de Lançamento', yaxis_title='Vendas Totais (em milhões USD)')
fig.show()

Parece que as únicas plataformas em ascenção são as novas: Xbox One (XOne) e Playstation 4 (PS4). O novo console da Nintendo WiiU vem tendo dificuldade de se estabelecer no mercado e repetir o sucesso do Wii. Vamos observar as medianas para entender uma visão do mercado com menos impacto dos grandes títulos.

In [392]:
# Calculando a mediana de vendas por plataforma para identificar quais plataformas têm bom potencial de vendas fora dos outliers
sales_by_platform = df_recent.groupby(['platform',]).agg(
                                                        {'total_sales': ['median', 'mean', 'sum'],
                                                        }).reset_index()

sales_by_platform.columns = ['platform', 'median_sales', 'mean_sales', 'total_sales']
sales_by_platform = sales_by_platform.sort_values('median_sales', ascending=False).reset_index(drop=True)

print(sales_by_platform)

   platform  median_sales  mean_sales  total_sales
0      X360          0.27    0.809426       550.41
1       PS3          0.23    0.661858       587.73
2      WiiU          0.22    0.559116        82.19
3      XOne          0.22    0.645020       159.32
4       PS4          0.20    0.801378       314.14
5       Wii          0.18    0.495489       222.97
6       3DS          0.12    0.503535       257.81
7        DS          0.10    0.244083       123.75
8        PC          0.08    0.254614       121.96
9       PSP          0.05    0.128100        64.05
10      PSV          0.05    0.125431        53.81

In [393]:
# Criando um gráfico de linha para visualizar a evolução das medianas de vendas por plataforma ao longo dos anos
fig = px.bar(sales_by_platform, x='platform', y='median_sales', color='platform', title='Evolução da Mediana de Vendas por Plataforma (Jogos Lançados a partir de 2010)', width=1400, height=800)
fig.update_layout(xaxis_title='Plataforma', yaxis_title='Mediana de Vendas (em milhões USD)')
fig.show()

#### Descobertas:

- O total de vendas de jogos é bastante influenciado por grandes títulos: alguns títulos de plataformas muito populares podem sozinho trazer mais receita que a receita anual de algumas plataformas. Kinect Adventures! para XBox 360 conquistou mais receita que todas as vendas de jogos para Wii e WiiU em 2012.
- Podemos observar XBox One e Playstation 4 ganhando espaço no mercado, enquanto suas gerações anteriores diminuem em vendas.
- Os consoles da Sony (Playstation) e Microsofot (Xbox) detem as maiores fatias do mercado, com os consoles da Nintendo tendo maior sucesso com portáteis (DS, 3DS) e dificuldade de conquistar muitas vendas com o sucessor do Wii, o WiiU. 
    - Ainda assim, desconsiderando o ano de 2016 (que pode ter dados ainda parciais), o WiiU vem mantendo uma fatia relativamente estável do mercado e as vendas de jogos performam com uma mediana similar (0.22M USD) a seus dois principais concorrentes XOne (0.22M USD) e PS4 (0.20M USD).