# Análise de vendas de jogos


> **Briefing:**
>
> Você trabalha para a loja online Ice, que vende videogames no mundo todo. As avaliações de usuários e especialistas, gêneros, plataformas (por exemplo, Xbox ou PlayStation) e dados históricos sobre vendas de jogos estão disponíveis em fontes abertas.
> Você precisa identificar padrões que determinam se um jogo tem sucesso ou não. Isso vai permitir que você identifique possíveis sucessos e planeje campanhas publicitárias.
>
> Os dados disponibilizados remontam a 2016. Vamos imaginar que estamos em dezembro de 2016 e você está planejando uma campanha para 2017.
>
> O conjunto de dados contém uma coluna de "rating" (classificação) que armazena a classificação ESRB de cada jogo. O Entertainment Software Rating Board avalia o conteúdo de um jogo e atribui uma classificação etária, como Teen (Adolescente) ou Mature (Adulto).

**Descrição dos dados:**

-  Name (nome)
-  Platform (plataforma)
-  Year_of_Release (Ano de lançamento)
-  Genre (gênero)
-  NA_sales (vendas norte-americanas em milhões de USD)
-  EU_sales (vendas na Europa em milhões de USD)
-  JP_sales (vendas no Japão em milhões de USD)
-  Other_sales (vendas em outros países em milhões de USD)
-  Critic_Score (Pontuação crítica) (máximo de 100)
-  User_Score (Pontuação dos usuários) (máximo de 10)
-  Classificação (ESRB)

## Plano de trabalho

1. Pré-processamento
    - <input type="checkbox" checked> Renomear colunas    
    - <input type="checkbox" checked> Avaliar colunas com dados vazios
        - <input type="checkbox" checked> Preencher, remover ou manter colunas com dados vazios
    - <input type="checkbox" checked> Investigar duplicatas
        - <input type="checkbox" checked> Corrigir ou remover duplicatas
    - <input type="checkbox" checked> Corrigir tipos de dados
    - <input type="checkbox" checked> Enriquecimento dos dados
        - <input type="checkbox" checked> Criar coluna total de vendas, com a soma de todas as regiões
        - <input type="checkbox" checked> Converter as avaliações de críticos e usuários para a mesma escala, para poder compará-las
2. Análise exploratória 
    - <input type="checkbox"> Quantos jogos foram lançados por ano?
    - <input type="checkbox"> Analisar as vendas por plataforma:
        - <input type="checkbox"> Quais são as plataformas mais populares?
        - <input type="checkbox"> Quantos jogos foram lançados para cada uma por ano?
        - <input type="checkbox"> Por quanto tempo uma plataforma se mantém relevante?
    - <input type="checkbox"> Definir quais dados são mais relevantes para uma análise preditiva para 2017
    - <input type="checkbox"> Analisar quais são as plataformas com maior potencial de vendas
        - <input type="checkbox"> Comparar a distribuição da distribuição das vendas entre as plataformas
        - <input type="checkbox"> Como as avaliações afetam as vendas?
    - <input type="checkbox"> Como se distribuem os jogos por gênero?
        - <input type="checkbox"> Quais são os gêneros mais populares? E os menos?
        - <input type="checkbox"> O que podemos generalizar sobre os gêneros com vendas altas e baixas?
3. Categorização por região
    - <input type="checkbox"> Quais são as principais plataformas de cada região?
        - <input type="checkbox"> Quanto elas detem de mercado em cada região?
    - <input type="checkbox"> Quais são os gêneros mais populares em cada região?
    - <input type="checkbox"> Como a classificação ESRB afeta as vendas em cada região?
4. Testes de hipóteses
    - <input type="checkbox"> Testar hipótese: As classificações médias dos usuários das plataformas Xbox One e PC são as mesmas.
    - <input type="checkbox"> Testar hipótese: As classificações médias de usuários para os gêneros Action (ação) e Sports (esportes) são diferentes.
5. Conclusão

## Inicialização

In [209]:
# Importando bibiliotecas
import numpy as np
import pandas as pd

In [210]:
# Importando o dataset
try:
    df = pd.read_csv('datasets/games.csv') # caminho local no windows
except FileNotFoundError:
    df = pd.read_csv('/datasets/games.csv') # caminho no ambiente da tripleten

In [211]:
# Visualizando os dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16713 non-null  object
 1   Platform         16715 non-null  object
 2   Year_of_Release  16446 non-null  float64
 3   Genre            16713 non-null  object
 4   NA_sales         16715 non-null  float64
 5   EU_sales         16715 non-null  float64
 6   JP_sales         16715 non-null  float64
 7   Other_sales      16715 non-null  float64
 8   Critic_Score     8137 non-null   float64
 9   User_Score       10014 non-null  object
 10  Rating           9949 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.4+ MB

In [212]:
# Visualizando as primeiras linhas do dataset
df.head()

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN

In [213]:
# Visualizando algumas amostras dos dados
df.sample(10, random_state=42)

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
3485,London 2012: The Official Video Game of the Ol...,X360,2012.0,Sports,0.07,0.44,0.00,0.07,NaN,NaN,NaN
5500,Etrian Odyssey,DS,2007.0,Role-Playing,0.19,0.02,0.09,0.02,75.0,8.5,T
16713,Spirits & Spells,GBA,2003.0,Platform,0.01,0.00,0.00,0.00,NaN,NaN,NaN
9489,RollerCoaster Tycoon,XB,2003.0,Strategy,0.10,0.03,0.00,0.00,62.0,8.3,E
12993,Rhapsody: A Musical Adventure,DS,2008.0,Role-Playing,0.05,0.00,0.00,0.00,67.0,6.8,E
12749,Men in Black The Series: Crashdown,PS,2001.0,Shooter,0.03,0.02,0.00,0.00,NaN,NaN,NaN
7270,Samurai Jack: The Amulet of Time,GBA,2003.0,Platform,0.16,0.06,0.00,0.00,63.0,tbd,T
2935,King Kong,2600,1981.0,Action,0.65,0.04,0.00,0.01,NaN,NaN,NaN
8739,Pressure Cooker,2600,1982.0,Action,0.14,0.01,0.00,0.00,NaN,NaN,NaN
2227,Cars,GC,2006.0,Racing,0.72,0.19,0.00,0.03,71.0,7,E

In [214]:
# Resumo estatístico das colunas numéricas
df.describe()

,Year_of_Release,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score
count,16446.000000,16715.000000,16715.000000,16715.000000,16715.000000,8137.000000
mean,2006.484616,0.263377,0.145060,0.077617,0.047342,68.967679
std,5.877050,0.813604,0.503339,0.308853,0.186731,13.938165
min,1980.000000,0.000000,0.000000,0.000000,0.000000,13.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,60.000000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,71.000000
75%,2010.000000,0.240000,0.110000,0.040000,0.030000,79.000000
max,2016.000000,41.360000,28.960000,10.220000,10.570000,98.000000

### Observações

**Formatação:**

- Renomear colunas para `snake_case` 

**Dados vazios:**

- Temos dados vazios em 6 colunas:
    - `Name`, `Year_of_Release`, `Genre` tem poucos valores vazios, avaliar possibilidade de remover as linhas
    - `Critics_Score`, `User_Score`, `Rating`: tem muitos valores, pode ser relevante pensar uma estratégia de preenchimento

**Tipos de dados:**

- Corrigir `Year_of_Release` de float para int, já que anos são inteiros
- `User_Score` precisa ser float, para realizarmos operações matemáticas, mas existem algumas linhas com a string 'tbd' que precisamos corrigir.

## Pré-processamento

In [215]:
# Renomeando colunas para snake_case
df.columns = df.columns.str.lower().str.replace(' ', '_')

# checando as colunas renomeadas
print(df.columns)
df.info()

Index(['name', 'platform', 'year_of_release', 'genre', 'na_sales', 'eu_sales',
       'jp_sales', 'other_sales', 'critic_score', 'user_score', 'rating'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16713 non-null  object
 1   platform         16715 non-null  object
 2   year_of_release  16446 non-null  float64
 3   genre            16713 non-null  object
 4   na_sales         16715 non-null  float64
 5   eu_sales         16715 non-null  float64
 6   jp_sales         16715 non-null  float64
 7   other_sales      16715 non-null  float64
 8   critic_score     8137 non-null   float64
 9   user_score       10014 non-null  object
 10  rating           9949 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.4+ MB

### Lidando com dados vazios

#### Colunas com poucas linhas vazias

In [216]:
# Checando vazios da coluna name
df[df['name'].isnull()]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
659,NaN,GEN,1993.0,NaN,1.78,0.53,0.00,0.08,NaN,NaN,NaN
14244,NaN,GEN,1993.0,NaN,0.00,0.00,0.03,0.00,NaN,NaN,NaN

In [217]:
# Checando vazios da coluna genre
df[df['genre'].isna()]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
659,NaN,GEN,1993.0,NaN,1.78,0.53,0.00,0.08,NaN,NaN,NaN
14244,NaN,GEN,1993.0,NaN,0.00,0.00,0.03,0.00,NaN,NaN,NaN

In [218]:
# Checando vazios da coluna year_of_release
df_year_null = df[df['year_of_release'].isna()]
print('Número de valores vazios na coluna year_of_release:', df['year_of_release'].isna().sum())
print(f'Porcentagem de jogos sem ano de lançamento: {(len(df_year_null) / len(df)) * 100:.2f}%')
print()
print(df_year_null['platform'].value_counts())

Número de valores vazios na coluna year_of_release: 269
Porcentagem de jogos sem ano de lançamento: 1.61%

platform
PS2     34
Wii     34
X360    30
DS      30
PS3     25
XB      21
2600    17
PC      17
PSP     16
GC      14
GBA     11
3DS      8
PS       7
N64      3
GB       1
PSV      1
Name: count, dtype: int64

In [219]:
df_year_null.head(10)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
183,Madden NFL 2004,PS2,NaN,Sports,4.26,0.26,0.01,0.71,94.0,8.5,E
377,FIFA Soccer 2004,PS2,NaN,Sports,0.59,2.36,0.04,0.51,84.0,6.4,E
456,LEGO Batman: The Videogame,Wii,NaN,Action,1.80,0.97,0.00,0.29,74.0,7.9,E10+
475,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,1.57,1.02,0.00,0.41,NaN,NaN,NaN
609,Space Invaders,2600,NaN,Shooter,2.36,0.14,0.00,0.03,NaN,NaN,NaN
627,Rock Band,X360,NaN,Misc,1.93,0.33,0.00,0.21,92.0,8.2,T
657,Frogger's Adventures: Temple of the Frog,GBA,NaN,Adventure,2.15,0.18,0.00,0.07,73.0,tbd,E
678,LEGO Indiana Jones: The Original Adventures,Wii,NaN,Action,1.51,0.61,0.00,0.21,78.0,6.6,E10+
719,Call of Duty 3,Wii,NaN,Shooter,1.17,0.84,0.00,0.23,69.0,6.7,T
805,Rock Band,Wii,NaN,Misc,1.33,0.56,0.00,0.20,80.0,6.3,T

In [220]:
# Removendo linhas valores vazios em year_of_release, name e genre
df = df.dropna(subset=['year_of_release', 'name', 'genre'])

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16444 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16444 non-null  object
 1   platform         16444 non-null  object
 2   year_of_release  16444 non-null  float64
 3   genre            16444 non-null  object
 4   na_sales         16444 non-null  float64
 5   eu_sales         16444 non-null  float64
 6   jp_sales         16444 non-null  float64
 7   other_sales      16444 non-null  float64
 8   critic_score     7983 non-null   float64
 9   user_score       9839 non-null   object
 10  rating           9768 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.5+ MB

##### Observações:
- As dados vazios de `name` e `genre` estão nas mesmas linhas, ambas foram removidas
- Decidi remover as linhas com dados vazio em `year_of_release` pois:
    - Apesar de alguns jogos terem vendas expressivas, o ano de lançamento é uma variável central para a análise temporal, preenche-lo pode tornar os resultados menos confiáveis
    - **1,61%** é um percentual aceitável dos dados para desconsiderar da análise.

#### Colunas com muitas linhas vazias

In [221]:
# Checando vazios da coluna critic_score
df_critic_null = df[df['critic_score'].isna()]
print('Número de valores vazios na coluna critic_score:', df['critic_score'].isna().sum())
print(f'Porcentagem de jogos sem critic_score: {(len(df_critic_null) / len(df)) * 100:.2f}%')

# Checando os valores únicos da coluna critic_score, incluindo os NaN
df['critic_score'].value_counts(dropna=False)

Número de valores vazios na coluna critic_score: 8461
Porcentagem de jogos sem critic_score: 51.45%

critic_score
NaN     8461
70.0     252
71.0     248
75.0     240
80.0     235
        ...
20.0       3
29.0       3
21.0       1
17.0       1
13.0       1
Name: count, Length: 82, dtype: int64

In [222]:
# Checando vazios da coluna user_score
df_user_null = df[df['user_score'].isna()]
print('Número de valores vazios na coluna user_score:', df['user_score'].isna().sum())
print(f'Porcentagem de jogos sem user_score: {(len(df_user_null) / len(df)) * 100:.2f}%')

# Checando os valores únicos da coluna user_score, incluindo os NaN
df['user_score'].value_counts(dropna=False)

Número de valores vazios na coluna user_score: 6605
Porcentagem de jogos sem user_score: 40.17%

user_score
NaN    6605
tbd    2376
7.8     322
8       285
8.2     276
       ...
1.9       2
9.6       2
0.9       2
0         1
9.7       1
Name: count, Length: 97, dtype: int64

In [223]:
# Checando vazios da coluna rating
df_rating_null = df[df['rating'].isna()]
print('Número de valores vazios na coluna rating:', df['rating'].isna().sum())
print(f'Porcentagem de jogos sem rating: {(len(df_rating_null) / len(df)) * 100:.2f}%')

# Checando os valores únicos da coluna rating, incluindo os NaN
df['rating'].value_counts(dropna=False)

Número de valores vazios na coluna rating: 6676
Porcentagem de jogos sem rating: 40.60%

rating
NaN     6676
E       3921
T       2905
M       1536
E10+    1393
EC         8
K-A        3
AO         1
RP         1
Name: count, dtype: int64

In [224]:
# Corrigindo os valores 'tbd' para NaN na coluna user_score
df['user_score'] = df['user_score'].replace('tbd', np.nan)

# Checando vazios da coluna user_score novamente após a correção
df_user_null = df[df['user_score'].isna()]
print('Número de valores vazios na coluna user_score:', df['user_score'].isna().sum())
print(f'Porcentagem de jogos sem user_score: {(len(df_user_null) / len(df)) * 100:.2f}%')

# Checando por virgulas nos scores e substituindo por pontos para garantir que sejam interpretados como números decimais
print('\nNúmero de valores com vírgula na coluna user_score: ', df['user_score'].str.contains(',', na=False).sum())

Número de valores vazios na coluna user_score: 8981
Porcentagem de jogos sem user_score: 54.62%

Número de valores com vírgula na coluna user_score:  0

In [225]:
# Substituindo NaN por 'N/A' na coluna rating
df['rating'] = df['rating'].fillna('N/A')

# Checando os valores únicos da coluna rating novamente, incluindo os NaN
print(df['rating'].value_counts(dropna=False))

rating
N/A     6676
E       3921
T       2905
M       1536
E10+    1393
EC         8
K-A        3
AO         1
RP         1
Name: count, dtype: int64

In [226]:
# Checando o dataframe após as limpezas
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16444 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16444 non-null  object
 1   platform         16444 non-null  object
 2   year_of_release  16444 non-null  float64
 3   genre            16444 non-null  object
 4   na_sales         16444 non-null  float64
 5   eu_sales         16444 non-null  float64
 6   jp_sales         16444 non-null  float64
 7   other_sales      16444 non-null  float64
 8   critic_score     7983 non-null   float64
 9   user_score       7463 non-null   object
 10  rating           16444 non-null  object
dtypes: float64(6), object(5)
memory usage: 1.5+ MB

#### Observações:
- Para coluna `rating` decidi preencher os valores vazios com N/A (Not Available) indicando que a classificação não está disponível. 
- Para `user_score` e `critic_score` a decisão foi de manter os valores vazios, pois:
    - Removê-los, significa perder um volume significativo dos dados (51%, apenas no caso de `critic_score`)
    - Substituir por 0 ou pela média/mediana introduziria um viés considerável nos dados e poderia distorcer análises
    - Mantê-los signfica que ao fazer análises de avaliação, trabalharemos com um subset menor dos dados, mas não compremetemos os resultados.
- Para `user_score`, ainda tinhamos uma quantidade considerável de linhas preenchidas com 'tbd' (To Be Defined), que decidi tratar como valores vazios. Substituindo-os para `NaN` para poder realizar a conversão para float.

### Checando duplicatas

In [227]:
# Checando por linhas duplicadas
print('Quantidade de linhas duplicadas:', df.duplicated().sum())

# Checando por linhas duplicadas considerando name, platform, year_of_release e genre
print('Quantidade de linhas duplicadas considerando name, platform, year_of_release e genre:', df.duplicated(subset=['name', 'platform', 'year_of_release', 'genre']).sum())

# Checando por duplicadas considerando apenas as colunas name, platform e year_of_release
print('Quantidade de linhas duplicadas considerando name, platform e year_of_release:', df.duplicated(subset=['name', 'platform', 'year_of_release']).sum())

# Checando por linhas duplicadas considerando name, platform, year_of_release e genre
print('Quantidade de linhas duplicadas considerando name, platform:', df.duplicated(subset=['name', 'platform']).sum())

Quantidade de linhas duplicadas: 0
Quantidade de linhas duplicadas considerando name, platform, year_of_release e genre: 1
Quantidade de linhas duplicadas considerando name, platform e year_of_release: 1
Quantidade de linhas duplicadas considerando name, platform: 3

In [228]:
# Imprimindo as linhas duplicadas considerando name e platform
duplicated_rows = df[df.duplicated(subset=['name', 'platform', 'year_of_release', 'genre'], keep=False)]
display(duplicated_rows)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
604,Madden NFL 13,PS3,2012.0,Sports,2.11,0.22,0.0,0.23,83.0,5.5,E
16230,Madden NFL 13,PS3,2012.0,Sports,0.00,0.01,0.0,0.00,83.0,5.5,E

In [229]:
# Removendo a linha duplicada
df = df.drop(index=16230)

# Checando o resultado
duplicated_rows = df[df.duplicated(subset=['name', 'platform', 'year_of_release', 'genre'], keep=False)]
display(duplicated_rows)

Empty DataFrame
Columns: [name, platform, year_of_release, genre, na_sales, eu_sales, jp_sales, other_sales, critic_score, user_score, rating]
Index: []

##### Observações:

- Encontrei uma instância de registro duplicado para o mesmo jogo, plataforma e ano de lançamento. 
- A coluna duplicada foi tratada como erro de registro, já que reproduzia o mesmos valores nos metadados e nas avaliações, além de 0 vendas em todas as regiões exceto em `eu_sales` com 0.01 (10 mil dólares), consideravelmente menor que o desvio padrão para `eu_sales` (~0.5), portanto estatisticamente pouco relevante.

### Corrigindo tipos de dados

In [230]:
# Convertendo year_of_release para inteiro
df['year_of_release'] = df['year_of_release'].astype(int)

# Convertendo user_score para float
df['user_score'] = pd.to_numeric(df['user_score'],errors='coerce')

# Checando se houve algum problema na conversão
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16443 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16443 non-null  object
 1   platform         16443 non-null  object
 2   year_of_release  16443 non-null  int64
 3   genre            16443 non-null  object
 4   na_sales         16443 non-null  float64
 5   eu_sales         16443 non-null  float64
 6   jp_sales         16443 non-null  float64
 7   other_sales      16443 non-null  float64
 8   critic_score     7982 non-null   float64
 9   user_score       7462 non-null   float64
 10  rating           16443 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 1.5+ MB

### Enriquecendo os dados

In [231]:
# Criando a coluna total_sales
df['total_sales'] = df['na_sales'] + df['eu_sales'] + df['jp_sales'] + df['other_sales']

# Checando o dataframe após a adição da coluna
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16443 entries, 0 to 16714
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16443 non-null  object
 1   platform         16443 non-null  object
 2   year_of_release  16443 non-null  int64
 3   genre            16443 non-null  object
 4   na_sales         16443 non-null  float64
 5   eu_sales         16443 non-null  float64
 6   jp_sales         16443 non-null  float64
 7   other_sales      16443 non-null  float64
 8   critic_score     7982 non-null   float64
 9   user_score       7462 non-null   float64
 10  rating           16443 non-null  object
 11  total_sales      16443 non-null  float64
dtypes: float64(7), int64(1), object(4)
memory usage: 1.6+ MB

In [232]:
# Exibindo uma amostra dos dados para verificar a nova coluna total_sales
df.sample(5, random_state=42)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,total_sales
4797,NCAA GameBreaker 2000,PS,1999,Sports,0.22,0.15,0.00,0.03,NaN,NaN,N/A,0.40
15039,Steel Battalion: Line of Contact,XB,2004,Simulation,0.02,0.01,0.00,0.00,70.0,8.0,T,0.03
9479,Shrek Super Party,XB,2002,Misc,0.10,0.03,0.00,0.00,33.0,8.0,E,0.13
8281,Hello Kitty: Happy Party Pals,GBA,2005,Misc,0.12,0.05,0.00,0.00,NaN,NaN,N/A,0.17
323,Call of Duty: Ghosts,PS4,2013,Shooter,1.78,1.43,0.05,0.57,78.0,3.7,M,3.83

In [233]:
# Multiplicando a coluna user_score por 10 para que fique na mesma escala do critic_score
df['user_score'] = df['user_score'] * 10

# Exibindo uma amostra dos dados para verificar a nova escala da coluna user_score
df.sample(5, random_state=42)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,total_sales
4797,NCAA GameBreaker 2000,PS,1999,Sports,0.22,0.15,0.00,0.03,NaN,NaN,N/A,0.40
15039,Steel Battalion: Line of Contact,XB,2004,Simulation,0.02,0.01,0.00,0.00,70.0,80.0,T,0.03
9479,Shrek Super Party,XB,2002,Misc,0.10,0.03,0.00,0.00,33.0,80.0,E,0.13
8281,Hello Kitty: Happy Party Pals,GBA,2005,Misc,0.12,0.05,0.00,0.00,NaN,NaN,N/A,0.17
323,Call of Duty: Ghosts,PS4,2013,Shooter,1.78,1.43,0.05,0.57,78.0,37.0,M,3.83

##### Observações:

- Foi criada uma coluna `total_sales` para poder fazer analises do total de vendas, independente da região.
- Multiplique a coluna `user_score` por 10, para que fique na mesma escala de `critic_score`, facilitando a comparação entre as duas em visualizações e eventuais operações artiméticas.

## Análise exploratória